server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
          routes:
            - id: blog-service
              uri: lb://BLOG-SERVICE
              predicates:
                - Path=/api/blogs/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
